/**
 * KINTRA — Canonical Brand State & Foundation Types
 *
 * Epistemic Taxonomy:
 * 1. Founder Input (raw statements directly entered by user)
 * 2. Extracted Facts (verified invariants extracted from founder input)
 * 3. Unresolved Questions (high-value unknowns requiring answers)
 * 4. Hypotheses (unverified strategic premises and market assumptions)
 * 5. AI Suggestions (candidate directions generated by models)
 * 6. Approved Decisions (explicitly locked strategic choices with rationale)
 * 7. Generated Artifacts (concrete launch deliverables derived from approved decisions)
 * 8. Validation Results (integrity, consistency, and anti-cliché audits)
 */

export type EpistemicSource = 'founder_input' | 'ai_extracted' | 'ai_generated' | 'user_approved' | 'user_edited';

export type AssumptionRiskLevel = 'low' | 'medium' | 'critical';

export interface ExtractedFact {
  id: string;
  statement: string;
  source: EpistemicSource;
  confidence: number; // 0.0 - 1.0
  verifiedByUser: boolean;
  createdAt: string;
}

export type InterviewTopic =
  | 'idea'
  | 'problem'
  | 'audience'
  | 'context'
  | 'alternatives'
  | 'value'
  | 'constraints'
  | 'desired_perception'
  | 'founder_intent';

export interface InterviewQuestion {
  id: string;
  topic: InterviewTopic;
  question: string;
  whyAsking: string; // Strategic rationale shown to user to build trust
  suggestedAnswers?: string[]; // Adaptive quick-select choices
  answerType: 'text' | 'choice' | 'hybrid';
  userAnswer?: string;
  skipped: boolean;
  askedAt?: string;
  answeredAt?: string;
}

export interface UnresolvedQuestion {
  id: string;
  topic: InterviewTopic;
  question: string;
  strategicImportance: 'essential' | 'helpful' | 'optional';
  whyItMatters: string;
  answer?: string;
  resolved: boolean;
}

export interface Hypothesis {
  id: string;
  claim: string;
  riskLevel: AssumptionRiskLevel;
  potentialConsequenceIfFalse: string;
  status: 'untested' | 'confirmed' | 'disproven' | 'refined';
  userNote?: string;
}

export interface IdeaBrief {
  id: string;
  version: number;
  problem: {
    corePain: string;
    whoSuffers: string;
    triggerEvent: string; // When does the pain occur?
  };
  targetUser: {
    primaryNiche: string;
    currentWorkarounds: string[];
    buyingTrigger: string;
  };
  context: {
    industryOrCategory: string;
    marketDynamics: string;
  };
  proposedValue: {
    mechanicOrSolution: string;
    keyBenefit: string;
    unfairAdvantage: string;
  };
  constraints: string[];
  assumptions: Hypothesis[];
  openQuestions: UnresolvedQuestion[];
  confidenceScore: number; // 0.0 - 1.0
  status: 'draft' | 'under_review' | 'approved' | 'rejected';
  generatedAt: string;
  approvedAt?: string;
  rejectionReason?: string;
}

export interface ApprovedDecision {
  id: string;
  category: 'problem_framing' | 'target_audience' | 'positioning' | 'name' | 'voice' | 'visual';
  title: string;
  value: string;
  rationale: string;
  approvedAt: string;
  approvedBy: 'founder';
  version: number;
  supersedesId?: string;
}

export interface GeneratedArtifact {
  id: string;
  type: 'idea_brief' | 'positioning_statement' | 'tagline' | 'voice_rules' | 'landing_page_hero' | 'launch_post';
  title: string;
  content: string;
  governingDecisionIds: string[];
  status: 'draft' | 'reviewed' | 'approved' | 'stale';
  createdAt: string;
  updatedAt: string;
}

export interface ValidationViolation {
  id: string;
  rule: string;
  severity: 'warning' | 'blocking';
  message: string;
  detectedText?: string;
  suggestedFix?: string;
}

export interface ValidationResult {
  id: string;
  stage: string;
  passed: boolean;
  score: number; // 0 - 100
  violations: ValidationViolation[];
  auditedAt: string;
}

export interface AdaptiveInterviewState {
  currentQuestionIndex: number;
  history: InterviewQuestion[];
  isComplete: boolean;
  lastUpdated: string;
}

export interface ProjectMetadata {
  id: string;
  name: string;
  slug: string;
  version: number;
  createdAt: string;
  updatedAt: string;
  isDemoProject?: boolean;
}

export interface ProjectSnapshot {
  id: string;
  version: number;
  label: string;
  timestamp: string;
  state: CanonicalBrandState;
}

import { MarketLandscape } from './research';
import { PositioningWorld, DecisionGraphState, ContradictionAlert } from './strategy';
import { CreativeIdentity } from './identity';
import { BrandArtifact } from './guardian';

export interface CanonicalBrandState {
  metadata: ProjectMetadata;
  stage:
    | 'intake'
    | 'discovery'
    | 'research'
    | 'positioning'
    | 'brief_review'
    | 'strategy_locked'
    | 'identity'
    | 'identity_locked'
    | 'guardian'
    | 'guardian_locked';
  rawFounderInput: string;
  extractedFacts: ExtractedFact[];
  unresolvedQuestions: UnresolvedQuestion[];
  hypotheses: Hypothesis[];
  interviewState: AdaptiveInterviewState;
  marketLandscape: MarketLandscape | null;
  positioningWorlds: PositioningWorld[];
  selectedWorldId: string | null;
  decisionGraph: DecisionGraphState;
  contradictions: ContradictionAlert[];
  ideaBrief: IdeaBrief | null;
  creativeIdentity: CreativeIdentity | null;
  decisions: Record<string, ApprovedDecision>;
  artifacts: GeneratedArtifact[];
  brandArtifacts?: BrandArtifact[];
  selectedArtifactId?: string | null;
  validationHistory: ValidationResult[];
}
